# Pre-commit hooks for aelus-aether
# Install: pre-commit install
# Run manually: pre-commit run --all-files
# Update hooks: pre-commit autoupdate

repos:
  # General file checks (fast)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: detect-private-key

  # Python code formatting with Ruff (fast and auto-fixes)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter with auto-fix (including unsafe fixes)
      - id: ruff
        args: [--fix, --unsafe-fixes]
      # Run the formatter
      - id: ruff-format

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.10.0
          - pydantic-settings>=2.6.0
          - types-redis
          - sqlalchemy[asyncio]>=2.0.36
          - fastapi>=0.115.0
        args: [--ignore-missing-imports, --check-untyped-defs, --no-strict-optional]
        files: ^(app|services|workers)/.*\.py$
        # Only check main application code, not tests or migrations

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -ll]  # -ll = only show medium/high severity
        additional_dependencies: ["bandit[toml]"]
        files: ^(app|services|workers)/.*\.py$
        # Skip tests directory as it has intentional test patterns

# Configuration for specific hooks
# default_language_version:
#   python: python3.12  # Use system default Python

# Files to exclude from all hooks
exclude: |
  (?x)^(
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    __pycache__/|
    \.venv/|
    venv/|
    build/|
    dist/|
    .*\.egg-info/|
    migrations/.*\.py$
  )
